data:
  in_memory: 1
  num_workers: 32
dist:
  world_size: 2
logging:
  folder: /tmp/
lr:
  lr: 0.5
  lr_schedule_type: cyclic
model:
  arch: resnet50
resolution:
  end_ramp: 299
  max_res: 192
  min_res: 160
  start_ramp: 298
training:
  batch_size: 192 
  bn_wd: 0
  distributed: 1
  epochs: 300 
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 256
