data:
  in_memory: 1
  num_workers: 32
dist:
  world_size: 2 
logging:
  folder: /tmp/
lr:
  lr: 0.05
  lr_schedule_type: cyclic
model:
  phi: 9 
resolution:
  end_ramp: 87 
  max_res: 224
  min_res: 224
  start_ramp: 86
training:
  batch_size: 196 
  bn_wd: 0
  distributed: 1
  epochs: 88
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 0
validation:
  lr_tta: true
  resolution: 256
