data:
  in_memory: 1
  num_workers: 32
dist:
  world_size: 2 
logging:
  folder: /tmp/
lr:
  lr: 0.05
  lr_schedule_type: cyclic
model:
  alpha: 1.2
  beta: 1.1
resolution:
  end_ramp: 19
  max_res: 224
  min_res: 224
  start_ramp: 18
training:
  batch_size: 512 
  bn_wd: 0
  distributed: 1
  epochs: 15 
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 0
validation:
  lr_tta: true
  resolution: 256
